### ISSUE TITLE
Example using google experiment

### ISSUE THREAD

**Issue by molinto** [omichelsen/express-ab#1]
Hi, great module!  Could you please add example when using Google Experiment.  Analytics require each variants to be unique paths but by using this module we only use 1 path per test.

Eg:  Google experiment requires each variant to be unique url:
www.domain.com/frontpage-1
www.domain.com/frontpage-2

But Express-AB, uses the same route (using express routes):
```
"frontpage": {
      "tests": [
        {
          "id": "YByMKfprRCStcMvK8zh1yw",
          "path": "/",
          "variants": [
            {
              "variantId": "frontpage-1column",
              "weighting": 0.5
            },
            {
              "variantId": "frontpage-2columns",
              "weighting": 0.5
            }
          ]
        }
      ]
```

**Comment by omichelsen** [comment]
I have updated the [README](https://github.com/omichelsen/express-ab/) with some more info about using Google Experiments.

You still have to specify unique URLs in GA, but you can just enter some fake hash/query string, it doesn't matter when you set the experiment variant programmatically.

**Comment by molinto** [comment]
Thanks :)
