### ISSUE TITLE
Changing distributions of a running test?

### ISSUE THREAD

**Issue by mattandrews** [omichelsen/express-ab#16]
Hi – thank you for this useful library and your work integrating Google Experiments. We're planning to launch a new homepage using your tool 😄 

One question, though: my plan is to launch a new page with 10% of the traffic seeing variant A (the new homepage) and the other 90% seeing variant B (the existing homepage).

Over time (say, a week) we want to ramp up this percentage when we become more confident the new page is performing well. Let's say we swap the percentages to 25/75.

What happens then to users who were already placed in a cohort? Any returning user who was shown variant B will have a cookie set, and will always see that page, even if the percentages switch to 90/10 (in favour of variant A), right?

One way I think I can get around this changing the cookie name at the same time I change percentage distributions, which should invalidate the previous cohorts. I wonder, though, if there's a better way to handle this. Maybe the cookie itself could be automatically set/named based on the percentage distributions, so a change to these would also change the cookie?

Thoughts welcome – this is probably a question around my particular usage of this code rather than any inherent bug, but I wanted to see if anyone else had any thoughts. Thanks!

**Comment by omichelsen** [comment]
Interesting use case. I don't see another way of doing it than you mention, by changing the cohort name when you adjust the the distribution.

I can't really think of an automated way of achieving this.

**Comment by mattandrews** [comment]
Thanks – no problem. Will use that technique!
