### ISSUE TITLE
How do I view a or b page in debug?

### ISSUE THREAD

**Issue by jinchizhong** [omichelsen/express-ab#2]
Hi friend

Thank you for your project.
I have a small question here, can you help me?

How do I view a page(or b page) unambiguous for debug purpose?

Thank you

**Comment by omichelsen** [comment]
Hey that rather depends on how your setup is. I would suggest to make an additional route to your options so they can be reached on a unique URL e.g.:

```
function variantA(req, res) {
    res.send('variant A');
}
function variantB(req, res) {
    res.send('variant B');
}
// ab test on root '/'
app.get('/', myPageTest(null, 0.2), variantA);
app.get('/', myPageTest(null, 0.8), variantB);
// access variants on '/a' or '/b'
app.get('/a', variantA);
app.get('/b', variantB);
```

Alternatively you can add some middleware that sniffs the querystring and bypasses the ab test.

**Comment by jinchizhong** [comment]
Thank you, this may be a good idea.
:p
