### ISSUE TITLE
Map variantId to Google Analysis Experiements 

### ISSUE THREAD

**Issue by tjlian616** [omichelsen/express-ab#22]
Thanks for the great work! I have a question about using this library with Google Analysis. 
The library gives variantId in locals as 0, 1, etc... So the source code looks like this
```
ga('set', 'expVar', '0');
```
I cannot find any reference online about how does this 0, 1 maps to the variant setup in Analysis. Does 0 maps to the original one?  All examples in Google's document seems to use number 1 as the variant ID so I'm worried that I might get the whole thing wrong.

**Comment by omichelsen** [comment]
If you have an A/B test called "myTest" with three different variants, they will have id's 0, 1 & 2. You can use this information in any way you like, you can send it to a logging service, Google Analytics or Google Analytics Experiments.

The example in the readme relates to [Google Analytics Experiments](https://developers.google.com/analytics/devguides/collection/analyticsjs/experiments) (GAE) where you have to send an ID and the variant index. It's up to you to make sure that your code gives the same index as the variants you have setup in GAE.
